name: Build in Repo A and Trigger Repo B

on:
  push:
    branches: [ main ]

jobs:
  build-and-trigger:
    runs-on: [self-hosted,linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Stuff
        run: echo "Building project in Repo A..."

      - name: Wait before triggering next workflow
        run: sleep 60

      - name: Trigger Repo B
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.TEST_SECRET }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Anvitha901/runners2/actions/workflows/actions-demo2.yml/dispatches \
            -d '{"ref":"main"}'
